const ActionTypes = {
  CHANGE_USER: "CHANGE_USER",
  FETCH_USERS: "FETCH_USERS",
  FETCH_USERS_FULFILLED: "FETCH_USERS_FULFILLED",
  FETCH_USERS_PENDING: " FETCH_USERS_PENDING",
  FETCH_USERS_REJECTED: "FETCH_USERS_REJECTED",
};

export default ActionTypes;
